apiVersion: batch/v1
kind: Job
metadata:
  name: "spp_for_k8s"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: "spp_for_k8s"
        image: "sail0603/mlproject:2.0"
        command: ["python /app/Stock_Price_Prediction.py"]
        #env: ["{appended-env-vars}"]
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
      restartPolicy: Never
